[phases.setup]
nixPkgs = ["python311"]

[phases.install]
# Usamos 'python -m pip' em vez de apenas 'pip' para garantir que ele encontre o instalador
cmds = ["python -m pip install --break-system-packages -r requirements.txt"]

[start]
# Verifique se o caminho do arquivo está correto (com ou sem a pasta 'backend/')
cmd = "python backend/server.py"